# Generated by Django 5.2.11 on 2026-02-04 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU/编码')),
                ('name', models.CharField(max_length=120, verbose_name='名称')),
                ('item_type', models.CharField(choices=[('material', '物料'), ('product', '成品')], default='material', max_length=20, verbose_name='类型')),
                ('unit', models.CharField(blank=True, default='件', max_length=20, verbose_name='单位')),
                ('qty_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='现存量')),
                ('min_qty', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='最低库存')),
            ],
            options={
                'verbose_name': '库存物料/成品',
                'verbose_name_plural': '库存物料/成品',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('customer_name', models.CharField(blank=True, default='', max_length=100, verbose_name='客户名称')),
                ('contact', models.CharField(blank=True, default='', max_length=100, verbose_name='联系人/电话')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('done', '已完成'), ('canceled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
            ],
            options={
                'verbose_name': '销售订单',
                'verbose_name_plural': '销售订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('wo_no', models.CharField(max_length=50, unique=True, verbose_name='工单号')),
                ('product_name', models.CharField(blank=True, default='', max_length=120, verbose_name='产品/项目')),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='数量')),
                ('status', models.CharField(choices=[('new', '新建'), ('in_progress', '生产中'), ('done', '已完工'), ('canceled', '已取消')], default='new', max_length=20, verbose_name='状态')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('so', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.salesorder', verbose_name='关联销售订单')),
            ],
            options={
                'verbose_name': '生产工单',
                'verbose_name_plural': '生产工单',
                'ordering': ['-created_at'],
            },
        ),
    ]
